### PR TITLE
fyi

### PR DESCRIPTION
**Pull request by zswgzx**
draft PR as requested.

working on first_level() but it runs long in my desktop, so unable to proceed for verification. secondlevel() is untouched.

### CODE REVIEW

**Comment by gdevenyi** [comment]
> working on first_level() but it runs long in my desktop
Downsample your inputs to 4x4x4mm to run faster.

**Comment by gdevenyi** [comment]
As per my request at https://github.com/CoBrALab/twolevel_ants_dbm/issues/59#issuecomment-841895441

I can't accept contributions without clear separated commits documenting each change in a way where they are reviewable. Please investigate using `git add -p` to separate out into coherent changes.

**Comment by zswgzx** [comment]
you mean one change at a time? 
will take me long to commit every single change, since the original code was, to my best experience, with all respect, written in a way that I feel extremely difficult to follow (hopefully not by intension). 
Refactoring it took me the full past Sunday and I still haven't done with secondlevel() yet. 
I'd suggest a pro programmer to do so if required. Sorry about that. Appreciate your time and effort.

**Comment by zswgzx** [comment]
I'll try the down sampled images as suggested.
My goal is to achieve exactly the same outputs using the original and my edited codes, and I'll still work on it. 
My lab has no clusters with slurm so I wonder if you'd be able to test, but I'm afraid I couldn't invest too much time on this any longer. I'd be happy to know any update from now on. Thank you.

**Pull request closed without merging**
